### ISSUE TITLE
Wrong intent for arguments to FCN() in example_lmder1.f90

### ISSUE THREAD

**Issue by xecej4** [certik/minpack#7]
The INTENT of arguments fvec and fjac of subroutine FCN should be changed from OUT to IN OUT. As of now, when the subroutine is entered with iflag = 1, fjac becomes undefined; when entered with iflag = another value, fvec becomes undefined. 

This subtle difference matters when flags such as NAG's -C=undefined or FTN95's /undef are used.

**Comment by certik** [comment]
I transferred this issue to https://github.com/fortran-lang/minpack/issues/21.
