### ISSUE TITLE
Archive repo?

### ISSUE THREAD

**Issue by awvwgk** [certik/minpack#8]
Should this project be archived and a link to [fortran-lang/minpack](https://github.com/fortran-lang/minpack) added to the README?

I also connected this repo content to the new fortran-lang version (see [`c0dc9cd`](https://github.com/fortran-lang/minpack/tree/c0dc9cd5453bcdf8ba4fe79561a660b20e2332a9)) to keep it available independently of the future status of this project.

**Comment by certik** [comment]
Yes. I don't have experience with archiving. I think we should first close all the issues and update the README and then archive.

**Comment by certik** [comment]
I updated README and moved the open issue. I am going to archive now.
